### ISSUE TITLE
Replace Vim with Vis

### ISSUE THREAD

**Issue by VehementHam** [glaucuslinux/glaucus#20]
https://github.com/martanne/vis/wiki/FAQ#why-dont-you-just-use-vim

Vis is a much better and less bloated alternative to Vim.

**Comment by firasuke** [comment]
Thanks for your interest in glaucus.

By replace `vim` with `vis`, you mean in the bootstrap process, because as a user you can choose whatever text editor you want.

That being said, I already have `vim` working just fine with `libedit` and `netbsd-curses`, and I have attempted to replace it with `vis` in the past, and it required adding more dependencies to the bootstrap process (e.g. `libtermkey`, `lpeg` and `tre`).

![image](https://github.com/glaucuslinux/glaucus/assets/46160727/0ad732b1-59c0-4105-b193-acc0067ad384)

**Comment by VehementHam** [comment]
Okay, thanks.

**Comment by firasuke** [comment]
No worries, thanks for your interest in glaucus!
